// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9oc6SKR6pBRSUTsN0MvA96ThiHM-uZg',
    appId: '1:88209575255:web:4fb7bf8b9c4a4b61c44212',
    messagingSenderId: '88209575255',
    projectId: 'aditiswadi-mdtest',
    authDomain: 'aditiswadi-mdtest.firebaseapp.com',
    storageBucket: 'aditiswadi-mdtest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe4wG5CFFGCFowCBzsH8-ZwONnKZD7aMQ',
    appId: '1:88209575255:android:ba28f4811b407ccac44212',
    messagingSenderId: '88209575255',
    projectId: 'aditiswadi-mdtest',
    storageBucket: 'aditiswadi-mdtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_SLOBnB9nh0gz6Wxm2vFcVNCdZM-KAc',
    appId: '1:88209575255:ios:98ed9c052ca8d7e3c44212',
    messagingSenderId: '88209575255',
    projectId: 'aditiswadi-mdtest',
    storageBucket: 'aditiswadi-mdtest.firebasestorage.app',
    iosBundleId: 'com.example.aditiswadiMdtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN_SLOBnB9nh0gz6Wxm2vFcVNCdZM-KAc',
    appId: '1:88209575255:ios:98ed9c052ca8d7e3c44212',
    messagingSenderId: '88209575255',
    projectId: 'aditiswadi-mdtest',
    storageBucket: 'aditiswadi-mdtest.firebasestorage.app',
    iosBundleId: 'com.example.aditiswadiMdtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9oc6SKR6pBRSUTsN0MvA96ThiHM-uZg',
    appId: '1:88209575255:web:48f1b167a7f2c59bc44212',
    messagingSenderId: '88209575255',
    projectId: 'aditiswadi-mdtest',
    authDomain: 'aditiswadi-mdtest.firebaseapp.com',
    storageBucket: 'aditiswadi-mdtest.firebasestorage.app',
  );
}
